server:
  port: 1121
  servlet:
    encoding:
      charset: UTF-8

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

spring:
  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.188.48.47:3306/MYDB?useUnicode=true&characterEncoding=utf8
    username: cyb
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true